
README for Examples
===================

fractional_yields.py
--------------------

This example demonstrates the calculation of the fractional yield functions that you will need to create a colour solid.
The data generated by this code is used by other examples.

vividness_calculation.py
------------------------

This is an example of calculating the vividness of a spectrum. We use extreme spectra as examples.

boundary_calculation.py
-----------------------

This demonstrates calculating a boundary spectrum. It is very much like vividness_calculation.py except that the
boundary spectrum and colour is never accessed at the script level.

plotting_and_exporting.py
-------------------------

This file has various examples of the plotting and exporting functionality of the ColourSolid class.